# Generated by Django 3.1.14 on 2023-04-03 06:17

from django.db import migrations
import django_mailbox.dav_media.fields
import django_mailbox.utils


class Migration(migrations.Migration):

    dependencies = [
        ('django_mailbox', '0008_auto_20190219_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='eml',
            field=django_mailbox.dav_media.fields.FileDavMedia(help_text='Original full content of message', null=True, upload_to='messages', verbose_name='Raw message contents'),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='document',
            field=django_mailbox.dav_media.fields.FileDavMedia(upload_to=django_mailbox.utils.get_attachment_save_path, verbose_name='Document'),
        ),
    ]
